name: Markdown linter
on:
  workflow_call:
    inputs:
      config_file:
        description: 'Path to the markdownlint configuration file - relative to the repository root'
        required: false
        type: string
        default: '.markdownlint-cli2.jsonc'
      context:
        required: false
        type: string
        default: 'markdown-linting'
        description: 'Identifier for the workflow when reporting status'

permissions:
  statuses: write
  contents: read

jobs:
  markdown-linter:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install markdownlint and gh dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g markdownlint-cli2
          gh extension install thetechcollective/gh-set-status --pin stable        

      - name: Markdown Linting
        id: markdown-linting
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
        run: |
          set +e
          # Use the configurable config file path - globs are defined in the config file
          echo '```' >> $GITHUB_STEP_SUMMARY
          markdownlint-cli2 --config ${{ inputs.config_file }} &>> $GITHUB_STEP_SUMMARY
          result=$?
          echo '```' >> $GITHUB_STEP_SUMMARY
          set -e
          if [ $result -eq 0 ]; then
            gh set-status success "All linting policy checks passed" "${{ inputs.context }}"
          else
            gh set-status failure "Some linting policy checks failed" "${{ inputs.context }}"
          fi
          exit $result